// Code generated by protoc-gen-go.
// source: github.com/Rakanixu/flag/srv/proto/flag/flag.proto
// DO NOT EDIT!

/*
Package go_micro_srv_flag is a generated protocol buffer package.

It is generated from these files:
	github.com/Rakanixu/flag/srv/proto/flag/flag.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	FlipRequest
	FlipResponse
	DeleteRequest
	DeleteResponse
	ListRequest
	ListResponse
*/
package go_micro_srv_flag

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CreateRequest struct {
	Key         string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Value       bool   `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadResponse struct {
	Key         string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Value       bool   `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FlipRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *FlipRequest) Reset()                    { *m = FlipRequest{} }
func (m *FlipRequest) String() string            { return proto.CompactTextString(m) }
func (*FlipRequest) ProtoMessage()               {}
func (*FlipRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type FlipResponse struct {
}

func (m *FlipResponse) Reset()                    { *m = FlipResponse{} }
func (m *FlipResponse) String() string            { return proto.CompactTextString(m) }
func (*FlipResponse) ProtoMessage()               {}
func (*FlipResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ListResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.flag.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.flag.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.flag.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.flag.ReadResponse")
	proto.RegisterType((*FlipRequest)(nil), "go.micro.srv.flag.FlipRequest")
	proto.RegisterType((*FlipResponse)(nil), "go.micro.srv.flag.FlipResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.flag.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.flag.DeleteResponse")
	proto.RegisterType((*ListRequest)(nil), "go.micro.srv.flag.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.flag.ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Flag service

type FlagClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Flip(ctx context.Context, in *FlipRequest, opts ...client.CallOption) (*FlipResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type flagClient struct {
	c           client.Client
	serviceName string
}

func NewFlagClient(serviceName string, c client.Client) FlagClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.flag"
	}
	return &flagClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *flagClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Flag.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Flag.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagClient) Flip(ctx context.Context, in *FlipRequest, opts ...client.CallOption) (*FlipResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Flag.Flip", in)
	out := new(FlipResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Flag.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Flag.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Flag service

type FlagHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Flip(context.Context, *FlipRequest, *FlipResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterFlagHandler(s server.Server, hdlr FlagHandler) {
	s.Handle(s.NewHandler(&Flag{hdlr}))
}

type Flag struct {
	FlagHandler
}

func (h *Flag) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.FlagHandler.Create(ctx, in, out)
}

func (h *Flag) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.FlagHandler.Read(ctx, in, out)
}

func (h *Flag) Flip(ctx context.Context, in *FlipRequest, out *FlipResponse) error {
	return h.FlagHandler.Flip(ctx, in, out)
}

func (h *Flag) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.FlagHandler.Delete(ctx, in, out)
}

func (h *Flag) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.FlagHandler.List(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x06, 0x41, 0xa2, 0xc3, 0x4f, 0x70, 0x63, 0x0c, 0xe1, 0x20, 0xd0, 0x83, 0xf1, 0xb4, 0x4d,
	0xf0, 0x11, 0x34, 0x24, 0x26, 0x26, 0x26, 0x3d, 0xe9, 0x71, 0x81, 0x11, 0x37, 0x14, 0xb6, 0xee,
	0x6e, 0x89, 0x3e, 0x82, 0x6f, 0x6d, 0xb7, 0xbb, 0x24, 0x8b, 0x6e, 0x39, 0x79, 0x69, 0x3a, 0x9d,
	0x6f, 0x66, 0xbe, 0x9f, 0x14, 0xa6, 0x2b, 0xae, 0xdf, 0xf3, 0x39, 0x5d, 0x88, 0x4d, 0x9c, 0xb0,
	0x35, 0xdb, 0xf2, 0xcf, 0x3c, 0x7e, 0x4b, 0xd9, 0x2a, 0x56, 0x72, 0x17, 0x67, 0x52, 0x68, 0x61,
	0x4b, 0xf3, 0xa0, 0x65, 0x4d, 0x2e, 0x56, 0x82, 0x6e, 0xf8, 0x42, 0x0a, 0x5a, 0x60, 0xa8, 0x69,
	0x44, 0xaf, 0xd0, 0xbd, 0x97, 0xc8, 0x34, 0x26, 0xf8, 0x91, 0xa3, 0xd2, 0xa4, 0x0f, 0x8d, 0x35,
	0x7e, 0x0d, 0xea, 0xe3, 0xfa, 0xed, 0x79, 0x62, 0x5e, 0xc9, 0x18, 0xda, 0x4b, 0x54, 0x0b, 0xc9,
	0x33, 0xcd, 0xc5, 0x76, 0x70, 0x52, 0x76, 0xfc, 0x4f, 0xe4, 0x12, 0x4e, 0x77, 0x2c, 0xcd, 0x71,
	0xd0, 0x28, 0x7a, 0x67, 0x89, 0x2d, 0xa2, 0x3e, 0xf4, 0xf6, 0xab, 0x55, 0x26, 0xb6, 0x0a, 0xa3,
	0x11, 0xb4, 0x13, 0x64, 0xcb, 0xca, 0x53, 0xd1, 0x0b, 0x74, 0x2c, 0xc0, 0x0e, 0xfc, 0x23, 0x99,
	0xe2, 0xf4, 0x2c, 0xe5, 0x59, 0xf5, 0xe9, 0x1e, 0x74, 0x2c, 0xc0, 0x71, 0x9d, 0x40, 0xf7, 0x01,
	0x53, 0x3c, 0x62, 0x8c, 0x11, 0xb8, 0x87, 0xb8, 0xa1, 0x2e, 0xb4, 0x9f, 0xb8, 0xd2, 0x6e, 0x24,
	0xba, 0x81, 0x8e, 0x2d, 0x9d, 0x9c, 0x2b, 0x68, 0x49, 0x54, 0x79, 0xaa, 0xdd, 0x16, 0x57, 0x4d,
	0xbf, 0x1b, 0xd0, 0x9c, 0x15, 0x69, 0x90, 0x67, 0x68, 0x59, 0xcb, 0xc8, 0x98, 0xfe, 0xc9, 0x8a,
	0x1e, 0x04, 0x35, 0x9c, 0x1c, 0x41, 0x38, 0x3a, 0x35, 0xf2, 0x08, 0x4d, 0x63, 0x28, 0xb9, 0x0e,
	0x80, 0xbd, 0x28, 0x86, 0xa3, 0xca, 0xbe, 0xbf, 0xca, 0x18, 0x14, 0x5c, 0xe5, 0x59, 0x1b, 0x5c,
	0x75, 0xe0, 0x6c, 0xcd, 0xc8, 0xb4, 0xc6, 0x05, 0x65, 0x1e, 0xd8, 0x1e, 0x94, 0xf9, 0xcb, 0xf5,
	0x92, 0x9b, 0x31, 0x3a, 0xc8, 0xcd, 0x0b, 0x24, 0xc8, 0xcd, 0x4f, 0x28, 0xaa, 0xcd, 0x5b, 0xe5,
	0xaf, 0x72, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0x47, 0x04, 0x8c, 0xef, 0x60, 0x03, 0x00, 0x00,
}
